#!/bin/bash

dt_system_dep(){

groupadd clash
useradd -g clash -d /home/clash -s /bin/bash -m clash

echo clash | sudo passwd clash --stdin  &>/dev/null

yes|apt -y install sudo supervisor iptables-persistent net-tools curl gzip unzip

echo "clash  ALL=(ALL:ALL) ALL" >> /etc/sudoers

cat << EOF > /etc/sysctl.conf
net.ipv4.ip_forward=1
fs.file-max = 999999
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 6291456
net.core.wmem_default = 6291456
net.core.netdev_max_backlog = 65535
net.core.somaxconn = 262114
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_mem = 8192 131072 67108864
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_orphans= 262114
net.ipv4.tcp_fastopen = 3
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.udp_mem = 8192 131072 67108864
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF

sysctl -p
}

#获取信息
dt_input(){
while [[ -z ${loc_ip} ]]; do
    loc_ip=$(whiptail --inputbox --nocancel "输入本机IP（现在安装灯塔客户端机器的ip）" 8 78 --title "输入域名" 3>&1 1>&2 2>&3)
done

while [[ -z ${gate_ip} ]]; do
    gate_ip=$(whiptail --inputbox --nocancel "输入网关IP（输入网关IP（ros的ip或者爱快ip）" 8 78 --title "输入域名" 3>&1 1>&2 2>&3)
done

while [[ -z ${dns} ]]; do
    dns=$(whiptail --inputbox --nocancel "输入dns（随你喜欢）" 8 78 --title "输入域名" 3>&1 1>&2 2>&3)
done

while [[ -z ${mtu} ]]; do
    mtu=$(whiptail --inputbox --nocancel "输入MTU" 8 78 --title "输入MTU" 3>&1 1>&2 2>&3)
done

while [[ -z ${mss} ]]; do
    mss=$(whiptail --inputbox --nocancel "输入MSS" 8 78 --title "输入MSS" 3>&1 1>&2 2>&3)
done
}


dt_smartdns(){

wget --no-check-certificate -O /opt/smartdns.deb $SM

cd /opt
dpkg -i smartdns.deb

cat << EOF > /etc/smartdns/smartdns.conf
server-name smartdns
bind :55
speed-check-mode tcp:443,tcp:80,ping
cache-size 60000
prefetch-domain yes
dualstack-ip-selection yes
dualstack-ip-selection-threshold 30
rr-ttl 3600
rr-ttl-min 300
rr-ttl-max 172800
log-level fatal
log-file /var/log/smartdns.log
log-size 2048k
log-num 2
conf-file /etc/smartdns/gfw_domain.conf
server 223.5.5.5
server 223.6.6.6
server 180.76.76.76
server 182.254.116.116
server 202.96.128.86
server 202.96.128.166
server202.96.134.33
server-tls 119.28.68.142:853
server-tls 107.155.79.120:853
server-tls 118.89.110.78:853
server-tls 47.96.179.163:853
server-https https://sdns.233py.com/dns-query
server-https https://ea-dns.rubyfish.cn/dns-query
EOF

rm -rf /opt/smartdns.deb

cd /etc/smartdns/

wget --no-check-certificate $GFW_LIST

cd 

systemctl enable smartdns
systemctl start smartdns > /dev/null 2>&1

}


dt_clash(){


wget --no-check-certificate -O /opt/clash.gz $CLS
cd /opt

gzip -d clash.gz
mv clash /usr/local/bin/clash
chmod +x /usr/local/bin/clash
# 为 clash 添加绑定低位端口的权限，这样运行 clash 的时候无需 root 权限
setcap cap_net_bind_service=+ep /usr/local/bin/clash

mkdir -p /home/clash/.config/clash

cat << EOF > /home/clash/.config/clash/config.yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 127.0.0.1:55
  fallback:
    - 127.0.0.1:55
secret: miyue
external-ui: dashboard
Proxy:
  - {name: $svr_domain, server: $svr_domain, port: 443, skip-cert-verify: true, type: trojan, password: $svr_pwd}
Proxy Group:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🎯 全球直连
      - $svr_domain
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - $svr_domain
  - name: 🎥 NETFLIX
    type: select
    proxies:
      - 🔰 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - $svr_domain
  - name: 🌌 YouTube
    type: select
    proxies:
      - 🔰 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - $svr_domain
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🔰 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - $svr_domain
  - name: 🌏 国内媒体
    type: select
    proxies:
      - 🎯 全球直连
      - 🔰 节点选择
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🔰 节点选择
      - $svr_domain
  - name: 📲 电报信息
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - $svr_domain
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - $svr_domain
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - $svr_domain
Rule:
 - DOMAIN-SUFFIX,local,🎯 全球直连
 - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,172.16.0.0/12,🎯 全球直连,no-resolve
 - IP-CIDR,127.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,100.64.0.0/10,🎯 全球直连,no-resolve
 - IP-CIDR6,::1/128,🎯 全球直连,no-resolve
 - IP-CIDR6,fc00::/7,🎯 全球直连,no-resolve
 - IP-CIDR6,fe80::/10,🎯 全球直连,no-resolve
 - IP-CIDR6,fd00::/8,🎯 全球直连,no-resolve
 - DOMAIN-KEYWORD,1drv,Ⓜ️ 微软服务
 - DOMAIN-KEYWORD,microsoft,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,aadrm.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,acompli.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,acompli.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,aka.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,akadns.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,aspnetcdn.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,assets-yammer.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,azure.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,azure.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,azureedge.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,azurerms.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,bing.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,cloudapp.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,cloudappsecurity.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,edgesuite.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,gfx.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,hotmail.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,live.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,live.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,lync.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msappproxy.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msauth.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msauthimages.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msecnd.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msedge.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msft.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msftauth.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msftauthimages.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msftidentity.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msidentity.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msn.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msocdn.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,msocsp.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,mstea.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,o365weve.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,oaspapps.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,office.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,office.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,office365.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,officeppe.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,omniroot.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,onedrive.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,onenote.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,onenote.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,onestore.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,outlook.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,outlookmobile.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,phonefactor.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,public-trust.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sfbassets.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sfx.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sharepoint.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sharepointonline.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,skype.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,skypeassets.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,skypeforbusiness.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,staffhub.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,svc.ms,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sway-cdn.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sway-extensions.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,sway.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,trafficmanager.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,uservoice.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,virtualearth.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,visualstudio.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,windows-ppe.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,windows.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,windows.net,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,windowsazure.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,windowsupdate.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,wunderlist.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,yammer.com,Ⓜ️ 微软服务
 - DOMAIN-SUFFIX,yammerusercontent.com,Ⓜ️ 微软服务
 - DOMAIN,app.adjust.com,🎯 全球直连
 - DOMAIN-SUFFIX,googletraveladservices.com,🎯 全球直连
 - DOMAIN,dl.google.com,🎯 全球直连
 - DOMAIN,mtalk.google.com,🎯 全球直连
 - DOMAIN,livew.l.qq.com,🎯 全球直连
 - DOMAIN,vd.l.qq.com,🎯 全球直连
 - DOMAIN,analytics.strava.com,🎯 全球直连
 - DOMAIN,msg.umeng.com,🎯 全球直连
 - DOMAIN,msg.umengcloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,fast.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflix.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflix.net,🎥 NETFLIX
 - DOMAIN-SUFFIX,nflxext.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,nflximg.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,nflximg.net,🎥 NETFLIX
 - DOMAIN-SUFFIX,nflxso.net,🎥 NETFLIX
 - DOMAIN-SUFFIX,nflxvideo.net,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest0.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest1.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest2.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest3.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest4.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest5.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest6.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest7.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest8.com,🎥 NETFLIX
 - DOMAIN-SUFFIX,netflixdnstest9.com,🎥 NETFLIX
 - IP-CIDR,23.246.0.0/18,🎥 NETFLIX,no-resolve
 - IP-CIDR,37.77.184.0/21,🎥 NETFLIX,no-resolve
 - IP-CIDR,45.57.0.0/17,🎥 NETFLIX,no-resolve
 - IP-CIDR,64.120.128.0/17,🎥 NETFLIX,no-resolve
 - IP-CIDR,66.197.128.0/17,🎥 NETFLIX,no-resolve
 - IP-CIDR,108.175.32.0/20,🎥 NETFLIX,no-resolve
 - IP-CIDR,192.173.64.0/18,🎥 NETFLIX,no-resolve
 - IP-CIDR,198.38.96.0/19,🎥 NETFLIX,no-resolve
 - IP-CIDR,198.45.48.0/20,🎥 NETFLIX,no-resolve
 - DOMAIN-SUFFIX,fast.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflix.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflix.net,🌌 YouTube
 - DOMAIN-SUFFIX,nflxext.com,🌌 YouTube
 - DOMAIN-SUFFIX,nflximg.com,🌌 YouTube
 - DOMAIN-SUFFIX,nflximg.net,🌌 YouTube
 - DOMAIN-SUFFIX,nflxso.net,🌌 YouTube
 - DOMAIN-SUFFIX,nflxvideo.net,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest0.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest1.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest2.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest3.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest4.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest5.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest6.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest7.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest8.com,🌌 YouTube
 - DOMAIN-SUFFIX,netflixdnstest9.com,🌌 YouTube
 - IP-CIDR,23.246.0.0/18,🌌 YouTube,no-resolve
 - IP-CIDR,37.77.184.0/21,🌌 YouTube,no-resolve
 - IP-CIDR,45.57.0.0/17,🌌 YouTube,no-resolve
 - IP-CIDR,64.120.128.0/17,🌌 YouTube,no-resolve
 - IP-CIDR,66.197.128.0/17,🌌 YouTube,no-resolve
 - IP-CIDR,108.175.32.0/20,🌌 YouTube,no-resolve
 - IP-CIDR,192.173.64.0/18,🌌 YouTube,no-resolve
 - IP-CIDR,198.38.96.0/19,🌌 YouTube,no-resolve
 - IP-CIDR,198.45.48.0/20,🌌 YouTube,no-resolve
 - DOMAIN-SUFFIX,deezer.com,🌍 国外媒体
 - DOMAIN-SUFFIX,dzcdn.net,🌍 国外媒体
 - DOMAIN-SUFFIX,kkbox.com,🌍 国外媒体
 - DOMAIN-SUFFIX,kkbox.com.tw,🌍 国外媒体
 - DOMAIN-SUFFIX,kfs.io,🌍 国外媒体
 - DOMAIN-SUFFIX,joox.com,🌍 国外媒体
 - DOMAIN-SUFFIX,pandora.com,🌍 国外媒体
 - DOMAIN-SUFFIX,p-cdn.us,🌍 国外媒体
 - DOMAIN-SUFFIX,sndcdn.com,🌍 国外媒体
 - DOMAIN-SUFFIX,soundcloud.com,🌍 国外媒体
 - DOMAIN-SUFFIX,pscdn.co,🌍 国外媒体
 - DOMAIN-SUFFIX,scdn.co,🌍 国外媒体
 - DOMAIN-SUFFIX,spotify.com,🌍 国外媒体
 - DOMAIN-SUFFIX,spoti.fi,🌍 国外媒体
 - DOMAIN-KEYWORD,spotify.com,🌍 国外媒体
 - DOMAIN-KEYWORD,-spotify-com,🌍 国外媒体
 - DOMAIN-SUFFIX,tidal.com,🌍 国外媒体
 - DOMAIN-SUFFIX,c4assets.com,🌍 国外媒体
 - DOMAIN-SUFFIX,channel4.com,🌍 国外媒体
 - DOMAIN-SUFFIX,abema.io,🌍 国外媒体
 - DOMAIN-SUFFIX,ameba.jp,🌍 国外媒体
 - DOMAIN-SUFFIX,abema.tv,🌍 国外媒体
 - DOMAIN-SUFFIX,hayabusa.io,🌍 国外媒体
 - DOMAIN,abematv.akamaized.net,🌍 国外媒体
 - DOMAIN,ds-linear-abematv.akamaized.net,🌍 国外媒体
 - DOMAIN,ds-vod-abematv.akamaized.net,🌍 国外媒体
 - DOMAIN,linear-abematv.akamaized.net,🌍 国外媒体
 - DOMAIN-SUFFIX,aiv-cdn.net,🌍 国外媒体
 - DOMAIN-SUFFIX,aiv-delivery.net,🌍 国外媒体
 - DOMAIN-SUFFIX,amazonvideo.com,🌍 国外媒体
 - DOMAIN-SUFFIX,primevideo.com,🌍 国外媒体
 - DOMAIN,avodmp4s3ww-a.akamaihd.net,🌍 国外媒体
 - DOMAIN,d25xi40x97liuc.cloudfront.net,🌍 国外媒体
 - DOMAIN,dmqdd6hw24ucf.cloudfront.net,🌍 国外媒体
 - DOMAIN,d22qjgkvxw22r6.cloudfront.net,🌍 国外媒体
 - DOMAIN,d1v5ir2lpwr8os.cloudfront.net,🌍 国外媒体
 - DOMAIN-KEYWORD,avoddashs,🌍 国外媒体
 - DOMAIN-SUFFIX,bahamut.com.tw,🌍 国外媒体
 - DOMAIN-SUFFIX,gamer.com.tw,🌍 国外媒体
 - DOMAIN,gamer-cds.cdn.hinet.net,🌍 国外媒体
 - DOMAIN,gamer2-cds.cdn.hinet.net,🌍 国外媒体
 - DOMAIN-SUFFIX,bbc.co.uk,🌍 国外媒体
 - DOMAIN-SUFFIX,bbci.co.uk,🌍 国外媒体
 - DOMAIN-KEYWORD,bbcfmt,🌍 国外媒体
 - DOMAIN-KEYWORD,uk-live,🌍 国外媒体
 - DOMAIN-SUFFIX,dazn.com,🌍 国外媒体
 - DOMAIN-SUFFIX,dazn-api.com,🌍 国外媒体
 - DOMAIN,d151l6v8er5bdm.cloudfront.net,🌍 国外媒体
 - DOMAIN-KEYWORD,voddazn,🌍 国外媒体
 - DOMAIN-SUFFIX,bamgrid.com,🌍 国外媒体
 - DOMAIN-SUFFIX,disney-plus.net,🌍 国外媒体
 - DOMAIN-SUFFIX,disneyplus.com,🌍 国外媒体
 - DOMAIN-SUFFIX,dssott.com,🌍 国外媒体
 - DOMAIN,cdn.registerdisney.go.com,🌍 国外媒体
 - DOMAIN-SUFFIX,encoretvb.com,🌍 国外媒体
 - DOMAIN,edge.api.brightcove.com,🌍 国外媒体
 - DOMAIN,bcbolt446c5271-a.akamaihd.net,🌍 国外媒体
 - DOMAIN-SUFFIX,fox.com,🌍 国外媒体
 - DOMAIN-SUFFIX,foxdcg.com,🌍 国外媒体
 - DOMAIN-SUFFIX,theplatform.com,🌍 国外媒体
 - DOMAIN-SUFFIX,uplynk.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hbo.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hbogo.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hbonow.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hbogoasia.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hbogoasia.hk,🌍 国外媒体
 - DOMAIN,bcbolthboa-a.akamaihd.net,🌍 国外媒体
 - DOMAIN,players.brightcove.net,🌍 国外媒体
 - DOMAIN,s3-ap-southeast-1.amazonaws.com,🌍 国外媒体
 - DOMAIN,dai3fd1oh325y.cloudfront.net,🌍 国外媒体
 - DOMAIN,44wilhpljf.execute-api.ap-southeast-1.amazonaws.com,🌍 国外媒体
 - DOMAIN,hboasia1-i.akamaihd.net,🌍 国外媒体
 - DOMAIN,hboasia2-i.akamaihd.net,🌍 国外媒体
 - DOMAIN,hboasia3-i.akamaihd.net,🌍 国外媒体
 - DOMAIN,hboasia4-i.akamaihd.net,🌍 国外媒体
 - DOMAIN,hboasia5-i.akamaihd.net,🌍 国外媒体
 - DOMAIN,cf-images.ap-southeast-1.prod.boltdns.net,🌍 国外媒体
 - DOMAIN-SUFFIX,5itv.tv,🌍 国外媒体
 - DOMAIN-SUFFIX,ocnttv.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hulu.com,🌍 国外媒体
 - DOMAIN-SUFFIX,huluim.com,🌍 国外媒体
 - DOMAIN-SUFFIX,hulustream.com,🌍 国外媒体
 - DOMAIN-SUFFIX,happyon.jp,🌍 国外媒体
 - DOMAIN-SUFFIX,hulu.jp,🌍 国外媒体
 - DOMAIN-SUFFIX,itv.com,🌍 国外媒体
 - DOMAIN-SUFFIX,itvstatic.com,🌍 国外媒体
 - DOMAIN,itvpnpmobile-a.akamaihd.net,🌍 国外媒体
 - DOMAIN-SUFFIX,kktv.com.tw,🌍 国外媒体
 - DOMAIN-SUFFIX,kktv.me,🌍 国外媒体
 - DOMAIN,kktv-theater.kk.stream,🌍 国外媒体
 - DOMAIN-SUFFIX,linetv.tw,🌍 国外媒体
 - DOMAIN,d3c7rimkq79yfu.cloudfront.net,🌍 国外媒体
 - DOMAIN-SUFFIX,litv.tv,🌍 国外媒体
 - DOMAIN,litvfreemobile-hichannel.cdn.hinet.net,🌍 国外媒体
 - DOMAIN-SUFFIX,channel5.com,🌍 国外媒体
 - DOMAIN-SUFFIX,my5.tv,🌍 国外媒体
 - DOMAIN,d349g9zuie06uo.cloudfront.net,🌍 国外媒体
 - DOMAIN-SUFFIX,mytvsuper.com,🌍 国外媒体
 - DOMAIN-SUFFIX,tvb.com,🌍 国外媒体
 - DOMAIN-SUFFIX,fast.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflix.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflix.net,🌍 国外媒体
 - DOMAIN-SUFFIX,nflxext.com,🌍 国外媒体
 - DOMAIN-SUFFIX,nflximg.com,🌍 国外媒体
 - DOMAIN-SUFFIX,nflximg.net,🌍 国外媒体
 - DOMAIN-SUFFIX,nflxso.net,🌍 国外媒体
 - DOMAIN-SUFFIX,nflxvideo.net,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest0.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest1.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest2.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest3.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest4.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest5.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest6.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest7.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest8.com,🌍 国外媒体
 - DOMAIN-SUFFIX,netflixdnstest9.com,🌍 国外媒体
 - IP-CIDR,23.246.0.0/18,🌍 国外媒体,no-resolve
 - IP-CIDR,37.77.184.0/21,🌍 国外媒体,no-resolve
 - IP-CIDR,45.57.0.0/17,🌍 国外媒体,no-resolve
 - IP-CIDR,64.120.128.0/17,🌍 国外媒体,no-resolve
 - IP-CIDR,66.197.128.0/17,🌍 国外媒体,no-resolve
 - IP-CIDR,108.175.32.0/20,🌍 国外媒体,no-resolve
 - IP-CIDR,192.173.64.0/18,🌍 国外媒体,no-resolve
 - IP-CIDR,198.38.96.0/19,🌍 国外媒体,no-resolve
 - IP-CIDR,198.45.48.0/20,🌍 国外媒体,no-resolve
 - DOMAIN-SUFFIX,dmc.nico,🌍 国外媒体
 - DOMAIN-SUFFIX,nicovideo.jp,🌍 国外媒体
 - DOMAIN-SUFFIX,nimg.jp,🌍 国外媒体
 - DOMAIN-SUFFIX,socdm.com,🌍 国外媒体
 - DOMAIN-SUFFIX,pbs.org,🌍 国外媒体
 - DOMAIN-SUFFIX,phncdn.com,🌍 国外媒体
 - DOMAIN-SUFFIX,phprcdn.com,🌍 国外媒体
 - DOMAIN-SUFFIX,pornhub.com,🌍 国外媒体
 - DOMAIN-SUFFIX,pornhubpremium.com,🌍 国外媒体
 - DOMAIN-SUFFIX,skyking.com.tw,🌍 国外媒体
 - DOMAIN,hamifans.emome.net,🌍 国外媒体
 - DOMAIN-SUFFIX,twitch.tv,🌍 国外媒体
 - DOMAIN-SUFFIX,twitchcdn.net,🌍 国外媒体
 - DOMAIN-SUFFIX,ttvnw.net,🌍 国外媒体
 - DOMAIN-SUFFIX,jtvnw.net,🌍 国外媒体
 - DOMAIN-SUFFIX,viu.com,🌍 国外媒体
 - DOMAIN-SUFFIX,viu.tv,🌍 国外媒体
 - DOMAIN,api.viu.now.com,🌍 国外媒体
 - DOMAIN,d1k2us671qcoau.cloudfront.net,🌍 国外媒体
 - DOMAIN,d2anahhhmp1ffz.cloudfront.net,🌍 国外媒体
 - DOMAIN,dfp6rglgjqszk.cloudfront.net,🌍 国外媒体
 - DOMAIN-SUFFIX,googlevideo.com,🌍 国外媒体
 - DOMAIN-SUFFIX,youtube.com,🌍 国外媒体
 - DOMAIN,youtubei.googleapis.com,🌍 国外媒体
 - DOMAIN-KEYWORD,bilibili,🌏 国内媒体
 - DOMAIN-SUFFIX,acg.tv,🌏 国内媒体
 - DOMAIN-SUFFIX,acgvideo.com,🌏 国内媒体
 - DOMAIN-SUFFIX,b23.tv,🌏 国内媒体
 - DOMAIN-SUFFIX,biliapi.com,🌏 国内媒体
 - DOMAIN-SUFFIX,biliapi.net,🌏 国内媒体
 - DOMAIN-SUFFIX,bilibili.com,🌏 国内媒体
 - DOMAIN-SUFFIX,biligame.com,🌏 国内媒体
 - DOMAIN-SUFFIX,biligame.net,🌏 国内媒体
 - DOMAIN-SUFFIX,bilivideo.com,🌏 国内媒体
 - DOMAIN-SUFFIX,hdslb.com,🌏 国内媒体
 - DOMAIN-SUFFIX,im9.com,🌏 国内媒体
 - DOMAIN-KEYWORD,qiyi,🌏 国内媒体
 - DOMAIN-SUFFIX,qy.net,🌏 国内媒体
 - IP-CIDR,101.227.0.0/16,🌏 国内媒体,no-resolve
 - IP-CIDR,101.224.0.0/13,🌏 国内媒体,no-resolve
 - IP-CIDR,119.176.0.0/12,🌏 国内媒体,no-resolve
 - DOMAIN-SUFFIX,api.mob.app.letv.com,🌏 国内媒体
 - DOMAIN-SUFFIX,vv.video.qq.com,🌏 国内媒体
 - IP-CIDR,106.11.0.0/16,🌏 国内媒体,no-resolve
 - DOMAIN-SUFFIX,t.me,📲 电报信息
 - DOMAIN-SUFFIX,tdesktop.com,📲 电报信息
 - DOMAIN-SUFFIX,telegra.ph,📲 电报信息
 - DOMAIN-SUFFIX,telegram.me,📲 电报信息
 - DOMAIN-SUFFIX,telegram.org,📲 电报信息
 - IP-CIDR,91.108.4.0/22,📲 电报信息,no-resolve
 - IP-CIDR,91.108.8.0/22,📲 电报信息,no-resolve
 - IP-CIDR,91.108.12.0/22,📲 电报信息,no-resolve
 - IP-CIDR,91.108.16.0/22,📲 电报信息,no-resolve
 - IP-CIDR,91.108.56.0/22,📲 电报信息,no-resolve
 - IP-CIDR,149.154.160.0/20,📲 电报信息,no-resolve
 - IP-CIDR6,2001:b28:f23d::/48,📲 电报信息,no-resolve
 - IP-CIDR6,2001:b28:f23f::/48,📲 电报信息,no-resolve
 - IP-CIDR6,2001:67c:4e8::/48,📲 电报信息,no-resolve
 - DOMAIN-SUFFIX,ampproject.org,🔰 节点选择
 - DOMAIN-SUFFIX,appspot.com,🔰 节点选择
 - DOMAIN-SUFFIX,blogger.com,🔰 节点选择
 - DOMAIN-SUFFIX,getoutline.org,🔰 节点选择
 - DOMAIN-SUFFIX,gvt0.com,🔰 节点选择
 - DOMAIN-SUFFIX,gvt1.com,🔰 节点选择
 - DOMAIN-SUFFIX,gvt3.com,🔰 节点选择
 - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🔰 节点选择
 - DOMAIN-KEYWORD,google,🔰 节点选择
 - DOMAIN-KEYWORD,blogspot,🔰 节点选择
 - DOMAIN-SUFFIX,onedrive.live.com,🔰 节点选择
 - DOMAIN-SUFFIX,xboxlive.com,🔰 节点选择
 - DOMAIN-SUFFIX,cdninstagram.com,🔰 节点选择
 - DOMAIN-SUFFIX,fb.com,🔰 节点选择
 - DOMAIN-SUFFIX,fb.me,🔰 节点选择
 - DOMAIN-SUFFIX,fbaddins.com,🔰 节点选择
 - DOMAIN-SUFFIX,fbcdn.net,🔰 节点选择
 - DOMAIN-SUFFIX,fbsbx.com,🔰 节点选择
 - DOMAIN-SUFFIX,fbworkmail.com,🔰 节点选择
 - DOMAIN-SUFFIX,instagram.com,🔰 节点选择
 - DOMAIN-SUFFIX,m.me,🔰 节点选择
 - DOMAIN-SUFFIX,messenger.com,🔰 节点选择
 - DOMAIN-SUFFIX,oculus.com,🔰 节点选择
 - DOMAIN-SUFFIX,oculuscdn.com,🔰 节点选择
 - DOMAIN-SUFFIX,rocksdb.org,🔰 节点选择
 - DOMAIN-SUFFIX,whatsapp.com,🔰 节点选择
 - DOMAIN-SUFFIX,whatsapp.net,🔰 节点选择
 - DOMAIN-KEYWORD,facebook,🔰 节点选择
 - IP-CIDR,3.123.36.126/32,🔰 节点选择,no-resolve
 - IP-CIDR,35.157.215.84/32,🔰 节点选择,no-resolve
 - IP-CIDR,35.157.217.255/32,🔰 节点选择,no-resolve
 - IP-CIDR,52.58.209.134/32,🔰 节点选择,no-resolve
 - IP-CIDR,54.93.124.31/32,🔰 节点选择,no-resolve
 - IP-CIDR,54.162.243.80/32,🔰 节点选择,no-resolve
 - IP-CIDR,54.173.34.141/32,🔰 节点选择,no-resolve
 - IP-CIDR,54.235.23.242/32,🔰 节点选择,no-resolve
 - IP-CIDR,169.45.248.118/32,🔰 节点选择,no-resolve
 - DOMAIN-SUFFIX,pscp.tv,🔰 节点选择
 - DOMAIN-SUFFIX,periscope.tv,🔰 节点选择
 - DOMAIN-SUFFIX,t.co,🔰 节点选择
 - DOMAIN-SUFFIX,twimg.co,🔰 节点选择
 - DOMAIN-SUFFIX,twimg.com,🔰 节点选择
 - DOMAIN-SUFFIX,twitpic.com,🔰 节点选择
 - DOMAIN-SUFFIX,vine.co,🔰 节点选择
 - DOMAIN-KEYWORD,twitter,🔰 节点选择
 - DOMAIN-SUFFIX,t.me,🔰 节点选择
 - DOMAIN-SUFFIX,tdesktop.com,🔰 节点选择
 - DOMAIN-SUFFIX,telegra.ph,🔰 节点选择
 - DOMAIN-SUFFIX,telegram.me,🔰 节点选择
 - DOMAIN-SUFFIX,telegram.org,🔰 节点选择
 - IP-CIDR,91.108.4.0/22,🔰 节点选择,no-resolve
 - IP-CIDR,91.108.8.0/22,🔰 节点选择,no-resolve
 - IP-CIDR,91.108.12.0/22,🔰 节点选择,no-resolve
 - IP-CIDR,91.108.16.0/22,🔰 节点选择,no-resolve
 - IP-CIDR,91.108.56.0/22,🔰 节点选择,no-resolve
 - IP-CIDR,149.154.160.0/20,🔰 节点选择,no-resolve
 - IP-CIDR6,2001:b28:f23d::/48,🔰 节点选择,no-resolve
 - IP-CIDR6,2001:b28:f23f::/48,🔰 节点选择,no-resolve
 - IP-CIDR6,2001:67c:4e8::/48,🔰 节点选择,no-resolve
 - DOMAIN-SUFFIX,line.me,🔰 节点选择
 - DOMAIN-SUFFIX,line-apps.com,🔰 节点选择
 - DOMAIN-SUFFIX,line-scdn.net,🔰 节点选择
 - DOMAIN-SUFFIX,naver.jp,🔰 节点选择
 - IP-CIDR,103.2.30.0/23,🔰 节点选择,no-resolve
 - IP-CIDR,125.209.208.0/20,🔰 节点选择,no-resolve
 - IP-CIDR,147.92.128.0/17,🔰 节点选择,no-resolve
 - IP-CIDR,203.104.144.0/21,🔰 节点选择,no-resolve
 - DOMAIN-SUFFIX,4shared.com,🔰 节点选择
 - DOMAIN-SUFFIX,520cc.cc,🔰 节点选择
 - DOMAIN-SUFFIX,881903.com,🔰 节点选择
 - DOMAIN-SUFFIX,9cache.com,🔰 节点选择
 - DOMAIN-SUFFIX,9gag.com,🔰 节点选择
 - DOMAIN-SUFFIX,abc.com,🔰 节点选择
 - DOMAIN-SUFFIX,abc.net.au,🔰 节点选择
 - DOMAIN-SUFFIX,abebooks.com,🔰 节点选择
 - DOMAIN-SUFFIX,amazon.co.jp,🔰 节点选择
 - DOMAIN-SUFFIX,apigee.com,🔰 节点选择
 - DOMAIN-SUFFIX,apk-dl.com,🔰 节点选择
 - DOMAIN-SUFFIX,apkfind.com,🔰 节点选择
 - DOMAIN-SUFFIX,apkmirror.com,🔰 节点选择
 - DOMAIN-SUFFIX,apkmonk.com,🔰 节点选择
 - DOMAIN-SUFFIX,apkpure.com,🔰 节点选择
 - DOMAIN-SUFFIX,aptoide.com,🔰 节点选择
 - DOMAIN-SUFFIX,archive.is,🔰 节点选择
 - DOMAIN-SUFFIX,archive.org,🔰 节点选择
 - DOMAIN-SUFFIX,arte.tv,🔰 节点选择
 - DOMAIN-SUFFIX,artstation.com,🔰 节点选择
 - DOMAIN-SUFFIX,arukas.io,🔰 节点选择
 - DOMAIN-SUFFIX,ask.com,🔰 节点选择
 - DOMAIN-SUFFIX,avg.com,🔰 节点选择
 - DOMAIN-SUFFIX,avgle.com,🔰 节点选择
 - DOMAIN-SUFFIX,badoo.com,🔰 节点选择
 - DOMAIN-SUFFIX,bandwagonhost.com,🔰 节点选择
 - DOMAIN-SUFFIX,bbc.com,🔰 节点选择
 - DOMAIN-SUFFIX,behance.net,🔰 节点选择
 - DOMAIN-SUFFIX,bibox.com,🔰 节点选择
 - DOMAIN-SUFFIX,biggo.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,binance.com,🔰 节点选择
 - DOMAIN-SUFFIX,bitcointalk.org,🔰 节点选择
 - DOMAIN-SUFFIX,bitfinex.com,🔰 节点选择
 - DOMAIN-SUFFIX,bitmex.com,🔰 节点选择
 - DOMAIN-SUFFIX,bit-z.com,🔰 节点选择
 - DOMAIN-SUFFIX,bloglovin.com,🔰 节点选择
 - DOMAIN-SUFFIX,bloomberg.cn,🔰 节点选择
 - DOMAIN-SUFFIX,bloomberg.com,🔰 节点选择
 - DOMAIN-SUFFIX,blubrry.com,🔰 节点选择
 - DOMAIN-SUFFIX,book.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,booklive.jp,🔰 节点选择
 - DOMAIN-SUFFIX,books.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,boslife.net,🔰 节点选择
 - DOMAIN-SUFFIX,box.com,🔰 节点选择
 - DOMAIN-SUFFIX,businessinsider.com,🔰 节点选择
 - DOMAIN-SUFFIX,bwh1.net,🔰 节点选择
 - DOMAIN-SUFFIX,castbox.fm,🔰 节点选择
 - DOMAIN-SUFFIX,cbc.ca,🔰 节点选择
 - DOMAIN-SUFFIX,cdw.com,🔰 节点选择
 - DOMAIN-SUFFIX,change.org,🔰 节点选择
 - DOMAIN-SUFFIX,channelnewsasia.com,🔰 节点选择
 - DOMAIN-SUFFIX,ck101.com,🔰 节点选择
 - DOMAIN-SUFFIX,clarionproject.org,🔰 节点选择
 - DOMAIN-SUFFIX,clyp.it,🔰 节点选择
 - DOMAIN-SUFFIX,cna.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,comparitech.com,🔰 节点选择
 - DOMAIN-SUFFIX,conoha.jp,🔰 节点选择
 - DOMAIN-SUFFIX,crucial.com,🔰 节点选择
 - DOMAIN-SUFFIX,cts.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,cw.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,cyberctm.com,🔰 节点选择
 - DOMAIN-SUFFIX,dailymotion.com,🔰 节点选择
 - DOMAIN-SUFFIX,dailyview.tw,🔰 节点选择
 - DOMAIN-SUFFIX,daum.net,🔰 节点选择
 - DOMAIN-SUFFIX,daumcdn.net,🔰 节点选择
 - DOMAIN-SUFFIX,dcard.tw,🔰 节点选择
 - DOMAIN-SUFFIX,deepdiscount.com,🔰 节点选择
 - DOMAIN-SUFFIX,depositphotos.com,🔰 节点选择
 - DOMAIN-SUFFIX,deviantart.com,🔰 节点选择
 - DOMAIN-SUFFIX,disconnect.me,🔰 节点选择
 - DOMAIN-SUFFIX,discordapp.com,🔰 节点选择
 - DOMAIN-SUFFIX,discordapp.net,🔰 节点选择
 - DOMAIN-SUFFIX,disqus.com,🔰 节点选择
 - DOMAIN-SUFFIX,dlercloud.com,🔰 节点选择
 - DOMAIN-SUFFIX,dns2go.com,🔰 节点选择
 - DOMAIN-SUFFIX,dowjones.com,🔰 节点选择
 - DOMAIN-SUFFIX,dropbox.com,🔰 节点选择
 - DOMAIN-SUFFIX,dropboxusercontent.com,🔰 节点选择
 - DOMAIN-SUFFIX,duckduckgo.com,🔰 节点选择
 - DOMAIN-SUFFIX,dw.com,🔰 节点选择
 - DOMAIN-SUFFIX,dynu.com,🔰 节点选择
 - DOMAIN-SUFFIX,earthcam.com,🔰 节点选择
 - DOMAIN-SUFFIX,ebookservice.tw,🔰 节点选择
 - DOMAIN-SUFFIX,economist.com,🔰 节点选择
 - DOMAIN-SUFFIX,edgecastcdn.net,🔰 节点选择
 - DOMAIN-SUFFIX,edu,🔰 节点选择
 - DOMAIN-SUFFIX,elpais.com,🔰 节点选择
 - DOMAIN-SUFFIX,enanyang.my,🔰 节点选择
 - DOMAIN-SUFFIX,encyclopedia.com,🔰 节点选择
 - DOMAIN-SUFFIX,esoir.be,🔰 节点选择
 - DOMAIN-SUFFIX,etherscan.io,🔰 节点选择
 - DOMAIN-SUFFIX,euronews.com,🔰 节点选择
 - DOMAIN-SUFFIX,evozi.com,🔰 节点选择
 - DOMAIN-SUFFIX,feedly.com,🔰 节点选择
 - DOMAIN-SUFFIX,firech.at,🔰 节点选择
 - DOMAIN-SUFFIX,flickr.com,🔰 节点选择
 - DOMAIN-SUFFIX,flitto.com,🔰 节点选择
 - DOMAIN-SUFFIX,foreignpolicy.com,🔰 节点选择
 - DOMAIN-SUFFIX,freebrowser.org,🔰 节点选择
 - DOMAIN-SUFFIX,freewechat.com,🔰 节点选择
 - DOMAIN-SUFFIX,freeweibo.com,🔰 节点选择
 - DOMAIN-SUFFIX,friday.tw,🔰 节点选择
 - DOMAIN-SUFFIX,ftchinese.com,🔰 节点选择
 - DOMAIN-SUFFIX,ftimg.net,🔰 节点选择
 - DOMAIN-SUFFIX,gate.io,🔰 节点选择
 - DOMAIN-SUFFIX,getlantern.org,🔰 节点选择
 - DOMAIN-SUFFIX,getsync.com,🔰 节点选择
 - DOMAIN-SUFFIX,globalvoices.org,🔰 节点选择
 - DOMAIN-SUFFIX,goo.ne.jp,🔰 节点选择
 - DOMAIN-SUFFIX,goodreads.com,🔰 节点选择
 - DOMAIN-SUFFIX,gov,🔰 节点选择
 - DOMAIN-SUFFIX,gov.tw,🔰 节点选择
 - DOMAIN-SUFFIX,greatfire.org,🔰 节点选择
 - DOMAIN-SUFFIX,gumroad.com,🔰 节点选择
 - DOMAIN-SUFFIX,hbg.com,🔰 节点选择
 - DOMAIN-SUFFIX,heroku.com,🔰 节点选择
 - DOMAIN-SUFFIX,hightail.com,🔰 节点选择
 - DOMAIN-SUFFIX,hk01.com,🔰 节点选择
 - DOMAIN-SUFFIX,hkbf.org,🔰 节点选择
 - DOMAIN-SUFFIX,hkbookcity.com,🔰 节点选择
 - DOMAIN-SUFFIX,hkej.com,🔰 节点选择
 - DOMAIN-SUFFIX,hket.com,🔰 节点选择
 - DOMAIN-SUFFIX,hkgolden.com,🔰 节点选择
 - DOMAIN-SUFFIX,hootsuite.com,🔰 节点选择
 - DOMAIN-SUFFIX,hudson.org,🔰 节点选择
 - DOMAIN-SUFFIX,hyread.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,ibtimes.com,🔰 节点选择
 - DOMAIN-SUFFIX,i-cable.com,🔰 节点选择
 - DOMAIN-SUFFIX,icij.org,🔰 节点选择
 - DOMAIN-SUFFIX,icoco.com,🔰 节点选择
 - DOMAIN-SUFFIX,imgur.com,🔰 节点选择
 - DOMAIN-SUFFIX,initiummall.com,🔰 节点选择
 - DOMAIN-SUFFIX,insecam.org,🔰 节点选择
 - DOMAIN-SUFFIX,ipfs.io,🔰 节点选择
 - DOMAIN-SUFFIX,issuu.com,🔰 节点选择
 - DOMAIN-SUFFIX,istockphoto.com,🔰 节点选择
 - DOMAIN-SUFFIX,japantimes.co.jp,🔰 节点选择
 - DOMAIN-SUFFIX,jiji.com,🔰 节点选择
 - DOMAIN-SUFFIX,jinx.com,🔰 节点选择
 - DOMAIN-SUFFIX,jkforum.net,🔰 节点选择
 - DOMAIN-SUFFIX,joinmastodon.org,🔰 节点选择
 - DOMAIN-SUFFIX,justmysocks.net,🔰 节点选择
 - DOMAIN-SUFFIX,justpaste.it,🔰 节点选择
 - DOMAIN-SUFFIX,kakao.com,🔰 节点选择
 - DOMAIN-SUFFIX,kakaocorp.com,🔰 节点选择
 - DOMAIN-SUFFIX,kik.com,🔰 节点选择
 - DOMAIN-SUFFIX,kobo.com,🔰 节点选择
 - DOMAIN-SUFFIX,kobobooks.com,🔰 节点选择
 - DOMAIN-SUFFIX,kodingen.com,🔰 节点选择
 - DOMAIN-SUFFIX,lemonde.fr,🔰 节点选择
 - DOMAIN-SUFFIX,lepoint.fr,🔰 节点选择
 - DOMAIN-SUFFIX,lihkg.com,🔰 节点选择
 - DOMAIN-SUFFIX,listennotes.com,🔰 节点选择
 - DOMAIN-SUFFIX,livestream.com,🔰 节点选择
 - DOMAIN-SUFFIX,logmein.com,🔰 节点选择
 - DOMAIN-SUFFIX,mail.ru,🔰 节点选择
 - DOMAIN-SUFFIX,mailchimp.com,🔰 节点选择
 - DOMAIN-SUFFIX,marc.info,🔰 节点选择
 - DOMAIN-SUFFIX,matters.news,🔰 节点选择
 - DOMAIN-SUFFIX,maying.co,🔰 节点选择
 - DOMAIN-SUFFIX,medium.com,🔰 节点选择
 - DOMAIN-SUFFIX,mega.nz,🔰 节点选择
 - DOMAIN-SUFFIX,mil,🔰 节点选择
 - DOMAIN-SUFFIX,mingpao.com,🔰 节点选择
 - DOMAIN-SUFFIX,mobile01.com,🔰 节点选择
 - DOMAIN-SUFFIX,myspace.com,🔰 节点选择
 - DOMAIN-SUFFIX,myspacecdn.com,🔰 节点选择
 - DOMAIN-SUFFIX,nanyang.com,🔰 节点选择
 - DOMAIN-SUFFIX,naver.com,🔰 节点选择
 - DOMAIN-SUFFIX,neowin.net,🔰 节点选择
 - DOMAIN-SUFFIX,newstapa.org,🔰 节点选择
 - DOMAIN-SUFFIX,nexitally.com,🔰 节点选择
 - DOMAIN-SUFFIX,nhk.or.jp,🔰 节点选择
 - DOMAIN-SUFFIX,nicovideo.jp,🔰 节点选择
 - DOMAIN-SUFFIX,nii.ac.jp,🔰 节点选择
 - DOMAIN-SUFFIX,nikkei.com,🔰 节点选择
 - DOMAIN-SUFFIX,nofile.io,🔰 节点选择
 - DOMAIN-SUFFIX,now.com,🔰 节点选择
 - DOMAIN-SUFFIX,nrk.no,🔰 节点选择
 - DOMAIN-SUFFIX,nyt.com,🔰 节点选择
 - DOMAIN-SUFFIX,nytchina.com,🔰 节点选择
 - DOMAIN-SUFFIX,nytcn.me,🔰 节点选择
 - DOMAIN-SUFFIX,nytco.com,🔰 节点选择
 - DOMAIN-SUFFIX,nytimes.com,🔰 节点选择
 - DOMAIN-SUFFIX,nytimg.com,🔰 节点选择
 - DOMAIN-SUFFIX,nytlog.com,🔰 节点选择
 - DOMAIN-SUFFIX,nytstyle.com,🔰 节点选择
 - DOMAIN-SUFFIX,ok.ru,🔰 节点选择
 - DOMAIN-SUFFIX,okex.com,🔰 节点选择
 - DOMAIN-SUFFIX,on.cc,🔰 节点选择
 - DOMAIN-SUFFIX,orientaldaily.com.my,🔰 节点选择
 - DOMAIN-SUFFIX,overcast.fm,🔰 节点选择
 - DOMAIN-SUFFIX,paltalk.com,🔰 节点选择
 - DOMAIN-SUFFIX,pao-pao.net,🔰 节点选择
 - DOMAIN-SUFFIX,parsevideo.com,🔰 节点选择
 - DOMAIN-SUFFIX,pbxes.com,🔰 节点选择
 - DOMAIN-SUFFIX,pcdvd.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,pchome.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,pcloud.com,🔰 节点选择
 - DOMAIN-SUFFIX,picacomic.com,🔰 节点选择
 - DOMAIN-SUFFIX,pinimg.com,🔰 节点选择
 - DOMAIN-SUFFIX,pixiv.net,🔰 节点选择
 - DOMAIN-SUFFIX,player.fm,🔰 节点选择
 - DOMAIN-SUFFIX,plurk.com,🔰 节点选择
 - DOMAIN-SUFFIX,po18.tw,🔰 节点选择
 - DOMAIN-SUFFIX,potato.im,🔰 节点选择
 - DOMAIN-SUFFIX,potatso.com,🔰 节点选择
 - DOMAIN-SUFFIX,prism-break.org,🔰 节点选择
 - DOMAIN-SUFFIX,proxifier.com,🔰 节点选择
 - DOMAIN-SUFFIX,pt.im,🔰 节点选择
 - DOMAIN-SUFFIX,pts.org.tw,🔰 节点选择
 - DOMAIN-SUFFIX,pubu.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,pubu.tw,🔰 节点选择
 - DOMAIN-SUFFIX,pureapk.com,🔰 节点选择
 - DOMAIN-SUFFIX,quora.com,🔰 节点选择
 - DOMAIN-SUFFIX,quoracdn.net,🔰 节点选择
 - DOMAIN-SUFFIX,rakuten.co.jp,🔰 节点选择
 - DOMAIN-SUFFIX,readingtimes.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,readmoo.com,🔰 节点选择
 - DOMAIN-SUFFIX,redbubble.com,🔰 节点选择
 - DOMAIN-SUFFIX,reddit.com,🔰 节点选择
 - DOMAIN-SUFFIX,redditmedia.com,🔰 节点选择
 - DOMAIN-SUFFIX,resilio.com,🔰 节点选择
 - DOMAIN-SUFFIX,reuters.com,🔰 节点选择
 - DOMAIN-SUFFIX,reutersmedia.net,🔰 节点选择
 - DOMAIN-SUFFIX,rfi.fr,🔰 节点选择
 - DOMAIN-SUFFIX,rixcloud.com,🔰 节点选择
 - DOMAIN-SUFFIX,roadshow.hk,🔰 节点选择
 - DOMAIN-SUFFIX,scmp.com,🔰 节点选择
 - DOMAIN-SUFFIX,scribd.com,🔰 节点选择
 - DOMAIN-SUFFIX,seatguru.com,🔰 节点选择
 - DOMAIN-SUFFIX,shadowsocks.org,🔰 节点选择
 - DOMAIN-SUFFIX,shopee.tw,🔰 节点选择
 - DOMAIN-SUFFIX,slideshare.net,🔰 节点选择
 - DOMAIN-SUFFIX,softfamous.com,🔰 节点选择
 - DOMAIN-SUFFIX,soundcloud.com,🔰 节点选择
 - DOMAIN-SUFFIX,ssrcloud.org,🔰 节点选择
 - DOMAIN-SUFFIX,startpage.com,🔰 节点选择
 - DOMAIN-SUFFIX,steamcommunity.com,🔰 节点选择
 - DOMAIN-SUFFIX,steemit.com,🔰 节点选择
 - DOMAIN-SUFFIX,steemitwallet.com,🔰 节点选择
 - DOMAIN-SUFFIX,t66y.com,🔰 节点选择
 - DOMAIN-SUFFIX,tapatalk.com,🔰 节点选择
 - DOMAIN-SUFFIX,teco-hk.org,🔰 节点选择
 - DOMAIN-SUFFIX,teco-mo.org,🔰 节点选择
 - DOMAIN-SUFFIX,teddysun.com,🔰 节点选择
 - DOMAIN-SUFFIX,textnow.me,🔰 节点选择
 - DOMAIN-SUFFIX,theguardian.com,🔰 节点选择
 - DOMAIN-SUFFIX,theinitium.com,🔰 节点选择
 - DOMAIN-SUFFIX,thetvdb.com,🔰 节点选择
 - DOMAIN-SUFFIX,tineye.com,🔰 节点选择
 - DOMAIN-SUFFIX,torproject.org,🔰 节点选择
 - DOMAIN-SUFFIX,tumblr.com,🔰 节点选择
 - DOMAIN-SUFFIX,turbobit.net,🔰 节点选择
 - DOMAIN-SUFFIX,tutanota.com,🔰 节点选择
 - DOMAIN-SUFFIX,tvboxnow.com,🔰 节点选择
 - DOMAIN-SUFFIX,udn.com,🔰 节点选择
 - DOMAIN-SUFFIX,unseen.is,🔰 节点选择
 - DOMAIN-SUFFIX,upmedia.mg,🔰 节点选择
 - DOMAIN-SUFFIX,uptodown.com,🔰 节点选择
 - DOMAIN-SUFFIX,urbandictionary.com,🔰 节点选择
 - DOMAIN-SUFFIX,ustream.tv,🔰 节点选择
 - DOMAIN-SUFFIX,uwants.com,🔰 节点选择
 - DOMAIN-SUFFIX,v2ray.com,🔰 节点选择
 - DOMAIN-SUFFIX,viber.com,🔰 节点选择
 - DOMAIN-SUFFIX,videopress.com,🔰 节点选择
 - DOMAIN-SUFFIX,vimeo.com,🔰 节点选择
 - DOMAIN-SUFFIX,voachinese.com,🔰 节点选择
 - DOMAIN-SUFFIX,voanews.com,🔰 节点选择
 - DOMAIN-SUFFIX,voxer.com,🔰 节点选择
 - DOMAIN-SUFFIX,vzw.com,🔰 节点选择
 - DOMAIN-SUFFIX,w3schools.com,🔰 节点选择
 - DOMAIN-SUFFIX,washingtonpost.com,🔰 节点选择
 - DOMAIN-SUFFIX,wattpad.com,🔰 节点选择
 - DOMAIN-SUFFIX,whoer.net,🔰 节点选择
 - DOMAIN-SUFFIX,wikimapia.org,🔰 节点选择
 - DOMAIN-SUFFIX,wikimedia.org,🔰 节点选择
 - DOMAIN-SUFFIX,wikipedia.org,🔰 节点选择
 - DOMAIN-SUFFIX,wikiquote.org,🔰 节点选择
 - DOMAIN-SUFFIX,wikiwand.com,🔰 节点选择
 - DOMAIN-SUFFIX,winudf.com,🔰 节点选择
 - DOMAIN-SUFFIX,wire.com,🔰 节点选择
 - DOMAIN-SUFFIX,wordpress.com,🔰 节点选择
 - DOMAIN-SUFFIX,workflow.is,🔰 节点选择
 - DOMAIN-SUFFIX,worldcat.org,🔰 节点选择
 - DOMAIN-SUFFIX,wsj.com,🔰 节点选择
 - DOMAIN-SUFFIX,wsj.net,🔰 节点选择
 - DOMAIN-SUFFIX,xhamster.com,🔰 节点选择
 - DOMAIN-SUFFIX,xn--90wwvt03e.com,🔰 节点选择
 - DOMAIN-SUFFIX,xn--i2ru8q2qg.com,🔰 节点选择
 - DOMAIN-SUFFIX,xnxx.com,🔰 节点选择
 - DOMAIN-SUFFIX,xvideos.com,🔰 节点选择
 - DOMAIN-SUFFIX,yahoo.com,🔰 节点选择
 - DOMAIN-SUFFIX,yandex.ru,🔰 节点选择
 - DOMAIN-SUFFIX,ycombinator.com,🔰 节点选择
 - DOMAIN-SUFFIX,yesasia.com,🔰 节点选择
 - DOMAIN-SUFFIX,yes-news.com,🔰 节点选择
 - DOMAIN-SUFFIX,yomiuri.co.jp,🔰 节点选择
 - DOMAIN-SUFFIX,you-get.org,🔰 节点选择
 - DOMAIN-SUFFIX,zaobao.com,🔰 节点选择
 - DOMAIN-SUFFIX,zb.com,🔰 节点选择
 - DOMAIN-SUFFIX,zello.com,🔰 节点选择
 - DOMAIN-SUFFIX,zeronet.io,🔰 节点选择
 - DOMAIN-SUFFIX,zoom.us,🔰 节点选择
 - DOMAIN-KEYWORD,github,🔰 节点选择
 - DOMAIN-KEYWORD,jav,🔰 节点选择
 - DOMAIN-KEYWORD,pinterest,🔰 节点选择
 - DOMAIN-KEYWORD,porn,🔰 节点选择
 - DOMAIN-KEYWORD,wikileaks,🔰 节点选择
 - DOMAIN-SUFFIX,apartmentratings.com,🔰 节点选择
 - DOMAIN-SUFFIX,apartments.com,🔰 节点选择
 - DOMAIN-SUFFIX,bankmobilevibe.com,🔰 节点选择
 - DOMAIN-SUFFIX,bing.com,🔰 节点选择
 - DOMAIN-SUFFIX,booktopia.com.au,🔰 节点选择
 - DOMAIN-SUFFIX,cccat.io,🔰 节点选择
 - DOMAIN-SUFFIX,centauro.com.br,🔰 节点选择
 - DOMAIN-SUFFIX,clearsurance.com,🔰 节点选择
 - DOMAIN-SUFFIX,costco.com,🔰 节点选择
 - DOMAIN-SUFFIX,crackle.com,🔰 节点选择
 - DOMAIN-SUFFIX,depositphotos.cn,🔰 节点选择
 - DOMAIN-SUFFIX,dish.com,🔰 节点选择
 - DOMAIN-SUFFIX,dmm.co.jp,🔰 节点选择
 - DOMAIN-SUFFIX,dmm.com,🔰 节点选择
 - DOMAIN-SUFFIX,dnvod.tv,🔰 节点选择
 - DOMAIN-SUFFIX,esurance.com,🔰 节点选择
 - DOMAIN-SUFFIX,extmatrix.com,🔰 节点选择
 - DOMAIN-SUFFIX,fastpic.ru,🔰 节点选择
 - DOMAIN-SUFFIX,flipboard.com,🔰 节点选择
 - DOMAIN-SUFFIX,fnac.be,🔰 节点选择
 - DOMAIN-SUFFIX,fnac.com,🔰 节点选择
 - DOMAIN-SUFFIX,funkyimg.com,🔰 节点选择
 - DOMAIN-SUFFIX,fxnetworks.com,🔰 节点选择
 - DOMAIN-SUFFIX,gettyimages.com,🔰 节点选择
 - DOMAIN-SUFFIX,go.com,🔰 节点选择
 - DOMAIN-SUFFIX,here.com,🔰 节点选择
 - DOMAIN-SUFFIX,jcpenney.com,🔰 节点选择
 - DOMAIN-SUFFIX,jiehua.tv,🔰 节点选择
 - DOMAIN-SUFFIX,mailfence.com,🔰 节点选择
 - DOMAIN-SUFFIX,nationwide.com,🔰 节点选择
 - DOMAIN-SUFFIX,nbc.com,🔰 节点选择
 - DOMAIN-SUFFIX,nexon.com,🔰 节点选择
 - DOMAIN-SUFFIX,nordstrom.com,🔰 节点选择
 - DOMAIN-SUFFIX,nordstromimage.com,🔰 节点选择
 - DOMAIN-SUFFIX,nordstromrack.com,🔰 节点选择
 - DOMAIN-SUFFIX,superpages.com,🔰 节点选择
 - DOMAIN-SUFFIX,target.com,🔰 节点选择
 - DOMAIN-SUFFIX,thinkgeek.com,🔰 节点选择
 - DOMAIN-SUFFIX,tracfone.com,🔰 节点选择
 - DOMAIN-SUFFIX,unity3d.com,🔰 节点选择
 - DOMAIN-SUFFIX,uploader.jp,🔰 节点选择
 - DOMAIN-SUFFIX,vevo.com,🔰 节点选择
 - DOMAIN-SUFFIX,viu.tv,🔰 节点选择
 - DOMAIN-SUFFIX,vk.com,🔰 节点选择
 - DOMAIN-SUFFIX,vsco.co,🔰 节点选择
 - DOMAIN-SUFFIX,xfinity.com,🔰 节点选择
 - DOMAIN-SUFFIX,zattoo.com,🔰 节点选择
 - DOMAIN,testflight.apple.com,🔰 节点选择
 - DOMAIN-SUFFIX,appsto.re,🔰 节点选择
 - DOMAIN,books.itunes.apple.com,🔰 节点选择
 - DOMAIN,hls.itunes.apple.com,🔰 节点选择
 - DOMAIN,apps.apple.com,🔰 节点选择
 - DOMAIN,itunes.apple.com,🔰 节点选择
 - DOMAIN,api-glb-sea.smoot.apple.com,🔰 节点选择
 - DOMAIN,lookup-api.apple.com,🔰 节点选择
 - DOMAIN-SUFFIX,abc.xyz,🔰 节点选择
 - DOMAIN-SUFFIX,android.com,🔰 节点选择
 - DOMAIN-SUFFIX,androidify.com,🔰 节点选择
 - DOMAIN-SUFFIX,dialogflow.com,🔰 节点选择
 - DOMAIN-SUFFIX,autodraw.com,🔰 节点选择
 - DOMAIN-SUFFIX,capitalg.com,🔰 节点选择
 - DOMAIN-SUFFIX,certificate-transparency.org,🔰 节点选择
 - DOMAIN-SUFFIX,chrome.com,🔰 节点选择
 - DOMAIN-SUFFIX,chromeexperiments.com,🔰 节点选择
 - DOMAIN-SUFFIX,chromestatus.com,🔰 节点选择
 - DOMAIN-SUFFIX,chromium.org,🔰 节点选择
 - DOMAIN-SUFFIX,creativelab5.com,🔰 节点选择
 - DOMAIN-SUFFIX,debug.com,🔰 节点选择
 - DOMAIN-SUFFIX,deepmind.com,🔰 节点选择
 - DOMAIN-SUFFIX,firebaseio.com,🔰 节点选择
 - DOMAIN-SUFFIX,getmdl.io,🔰 节点选择
 - DOMAIN-SUFFIX,ggpht.com,🔰 节点选择
 - DOMAIN-SUFFIX,gmail.com,🔰 节点选择
 - DOMAIN-SUFFIX,gmodules.com,🔰 节点选择
 - DOMAIN-SUFFIX,godoc.org,🔰 节点选择
 - DOMAIN-SUFFIX,golang.org,🔰 节点选择
 - DOMAIN-SUFFIX,gstatic.com,🔰 节点选择
 - DOMAIN-SUFFIX,gv.com,🔰 节点选择
 - DOMAIN-SUFFIX,gwtproject.org,🔰 节点选择
 - DOMAIN-SUFFIX,itasoftware.com,🔰 节点选择
 - DOMAIN-SUFFIX,madewithcode.com,🔰 节点选择
 - DOMAIN-SUFFIX,material.io,🔰 节点选择
 - DOMAIN-SUFFIX,polymer-project.org,🔰 节点选择
 - DOMAIN-SUFFIX,admin.recaptcha.net,🔰 节点选择
 - DOMAIN-SUFFIX,recaptcha.net,🔰 节点选择
 - DOMAIN-SUFFIX,shattered.io,🔰 节点选择
 - DOMAIN-SUFFIX,synergyse.com,🔰 节点选择
 - DOMAIN-SUFFIX,tensorflow.org,🔰 节点选择
 - DOMAIN-SUFFIX,tfhub.dev,🔰 节点选择
 - DOMAIN-SUFFIX,tiltbrush.com,🔰 节点选择
 - DOMAIN-SUFFIX,waveprotocol.org,🔰 节点选择
 - DOMAIN-SUFFIX,waymo.com,🔰 节点选择
 - DOMAIN-SUFFIX,webmproject.org,🔰 节点选择
 - DOMAIN-SUFFIX,webrtc.org,🔰 节点选择
 - DOMAIN-SUFFIX,whatbrowser.org,🔰 节点选择
 - DOMAIN-SUFFIX,widevine.com,🔰 节点选择
 - DOMAIN-SUFFIX,x.company,🔰 节点选择
 - DOMAIN-SUFFIX,youtu.be,🔰 节点选择
 - DOMAIN-SUFFIX,yt.be,🔰 节点选择
 - DOMAIN-SUFFIX,ytimg.com,🔰 节点选择
 - DOMAIN-SUFFIX,1drv.com,🔰 节点选择
 - DOMAIN-SUFFIX,1drv.ms,🔰 节点选择
 - DOMAIN-SUFFIX,blob.core.windows.net,🔰 节点选择
 - DOMAIN-SUFFIX,livefilestore.com,🔰 节点选择
 - DOMAIN-SUFFIX,onedrive.com,🔰 节点选择
 - DOMAIN-SUFFIX,storage.live.com,🔰 节点选择
 - DOMAIN-SUFFIX,storage.msn.com,🔰 节点选择
 - DOMAIN,oneclient.sfx.ms,🔰 节点选择
 - DOMAIN-SUFFIX,0rz.tw,🔰 节点选择
 - DOMAIN-SUFFIX,4bluestones.biz,🔰 节点选择
 - DOMAIN-SUFFIX,9bis.net,🔰 节点选择
 - DOMAIN-SUFFIX,allconnected.co,🔰 节点选择
 - DOMAIN-SUFFIX,aol.com,🔰 节点选择
 - DOMAIN-SUFFIX,bcc.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,bit.ly,🔰 节点选择
 - DOMAIN-SUFFIX,bitshare.com,🔰 节点选择
 - DOMAIN-SUFFIX,blog.jp,🔰 节点选择
 - DOMAIN-SUFFIX,blogimg.jp,🔰 节点选择
 - DOMAIN-SUFFIX,blogtd.org,🔰 节点选择
 - DOMAIN-SUFFIX,broadcast.co.nz,🔰 节点选择
 - DOMAIN-SUFFIX,camfrog.com,🔰 节点选择
 - DOMAIN-SUFFIX,cfos.de,🔰 节点选择
 - DOMAIN-SUFFIX,citypopulation.de,🔰 节点选择
 - DOMAIN-SUFFIX,cloudfront.net,🔰 节点选择
 - DOMAIN-SUFFIX,ctitv.com.tw,🔰 节点选择
 - DOMAIN-SUFFIX,cuhk.edu.hk,🔰 节点选择
 - DOMAIN-SUFFIX,cusu.hk,🔰 节点选择
 - DOMAIN-SUFFIX,discord.gg,🔰 节点选择
 - DOMAIN-SUFFIX,discuss.com.hk,🔰 节点选择
 - DOMAIN-SUFFIX,dropboxapi.com,🔰 节点选择
 - DOMAIN-SUFFIX,duolingo.cn,🔰 节点选择
 - DOMAIN-SUFFIX,edditstatic.com,🔰 节点选择
 - DOMAIN-SUFFIX,flickriver.com,🔰 节点选择
 - DOMAIN-SUFFIX,focustaiwan.tw,🔰 节点选择
 - DOMAIN-SUFFIX,free.fr,🔰 节点选择
 - DOMAIN-SUFFIX,gigacircle.com,🔰 节点选择
 - DOMAIN-SUFFIX,hk-pub.com,🔰 节点选择
 - DOMAIN-SUFFIX,hosting.co.uk,🔰 节点选择
 - DOMAIN-SUFFIX,hwcdn.net,🔰 节点选择
 - DOMAIN-SUFFIX,ifixit.com,🔰 节点选择
 - DOMAIN-SUFFIX,iphone4hongkong.com,🔰 节点选择
 - DOMAIN-SUFFIX,iphonetaiwan.org,🔰 节点选择
 - DOMAIN-SUFFIX,iptvbin.com,🔰 节点选择
 - DOMAIN-SUFFIX,linksalpha.com,🔰 节点选择
 - DOMAIN-SUFFIX,manyvids.com,🔰 节点选择
 - DOMAIN-SUFFIX,myactimes.com,🔰 节点选择
 - DOMAIN-SUFFIX,newsblur.com,🔰 节点选择
 - DOMAIN-SUFFIX,now.im,🔰 节点选择
 - DOMAIN-SUFFIX,nowe.com,🔰 节点选择
 - DOMAIN-SUFFIX,redditlist.com,🔰 节点选择
 - DOMAIN-SUFFIX,s3.amazonaws.com,🔰 节点选择
 - DOMAIN-SUFFIX,signal.org,🔰 节点选择
 - DOMAIN-SUFFIX,smartmailcloud.com,🔰 节点选择
 - DOMAIN-SUFFIX,sparknotes.com,🔰 节点选择
 - DOMAIN-SUFFIX,streetvoice.com,🔰 节点选择
 - DOMAIN-SUFFIX,supertop.co,🔰 节点选择
 - DOMAIN-SUFFIX,tv.com,🔰 节点选择
 - DOMAIN-SUFFIX,typepad.com,🔰 节点选择
 - DOMAIN-SUFFIX,udnbkk.com,🔰 节点选择
 - DOMAIN-SUFFIX,urbanairship.com,🔰 节点选择
 - DOMAIN-SUFFIX,whispersystems.org,🔰 节点选择
 - DOMAIN-SUFFIX,wikia.com,🔰 节点选择
 - DOMAIN-SUFFIX,wn.com,🔰 节点选择
 - DOMAIN-SUFFIX,wolframalpha.com,🔰 节点选择
 - DOMAIN-SUFFIX,x-art.com,🔰 节点选择
 - DOMAIN-SUFFIX,yimg.com,🔰 节点选择
 - DOMAIN,api.steampowered.com,🔰 节点选择
 - DOMAIN,store.steampowered.com,🔰 节点选择
 - DOMAIN-SUFFIX,aaplimg.com,🍎 苹果服务
 - DOMAIN-SUFFIX,apple.co,🍎 苹果服务
 - DOMAIN-SUFFIX,apple.com,🍎 苹果服务
 - DOMAIN-SUFFIX,apple-cloudkit.com,🍎 苹果服务
 - DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
 - DOMAIN-SUFFIX,cdn-apple.com,🍎 苹果服务
 - DOMAIN-SUFFIX,crashlytics.com,🍎 苹果服务
 - DOMAIN-SUFFIX,icloud.com,🍎 苹果服务
 - DOMAIN-SUFFIX,icloud-content.com,🍎 苹果服务
 - DOMAIN-SUFFIX,me.com,🍎 苹果服务
 - DOMAIN-SUFFIX,mzstatic.com,🍎 苹果服务
 - DOMAIN,www-cdn.icloud.com.akadns.net,🍎 苹果服务
 - DOMAIN-SUFFIX,qhres.com,🎯 全球直连
 - DOMAIN-SUFFIX,qhimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,akadns.net,🎯 全球直连
 - DOMAIN-SUFFIX,alibaba.com,🎯 全球直连
 - DOMAIN-SUFFIX,alicdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,alikunlun.com,🎯 全球直连
 - DOMAIN-SUFFIX,alipay.com,🎯 全球直连
 - DOMAIN-SUFFIX,amap.com,🎯 全球直连
 - DOMAIN-SUFFIX,autonavi.com,🎯 全球直连
 - DOMAIN-SUFFIX,dingtalk.com,🎯 全球直连
 - DOMAIN-SUFFIX,mxhichina.com,🎯 全球直连
 - DOMAIN-SUFFIX,soku.com,🎯 全球直连
 - DOMAIN-SUFFIX,taobao.com,🎯 全球直连
 - DOMAIN-SUFFIX,tmall.com,🎯 全球直连
 - DOMAIN-SUFFIX,tmall.hk,🎯 全球直连
 - DOMAIN-SUFFIX,ykimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,youku.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiami.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiami.net,🎯 全球直连
 - DOMAIN-SUFFIX,aaplimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,apple.co,🎯 全球直连
 - DOMAIN-SUFFIX,apple.com,🎯 全球直连
 - DOMAIN-SUFFIX,apple-cloudkit.com,🎯 全球直连
 - DOMAIN-SUFFIX,appstore.com,🎯 全球直连
 - DOMAIN-SUFFIX,cdn-apple.com,🎯 全球直连
 - DOMAIN-SUFFIX,crashlytics.com,🎯 全球直连
 - DOMAIN-SUFFIX,icloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,icloud-content.com,🎯 全球直连
 - DOMAIN-SUFFIX,me.com,🎯 全球直连
 - DOMAIN-SUFFIX,mzstatic.com,🎯 全球直连
 - DOMAIN,www-cdn.icloud.com.akadns.net,🎯 全球直连
 - DOMAIN-SUFFIX,baidu.com,🎯 全球直连
 - DOMAIN-SUFFIX,baidubcr.com,🎯 全球直连
 - DOMAIN-SUFFIX,bdstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,yunjiasu-cdn.net,🎯 全球直连
 - DOMAIN-SUFFIX,acgvideo.com,🎯 全球直连
 - DOMAIN-SUFFIX,biliapi.com,🎯 全球直连
 - DOMAIN-SUFFIX,biliapi.net,🎯 全球直连
 - DOMAIN-SUFFIX,bilibili.com,🎯 全球直连
 - DOMAIN-SUFFIX,bilibili.tv,🎯 全球直连
 - DOMAIN-SUFFIX,hdslb.com,🎯 全球直连
 - DOMAIN-SUFFIX,blizzard.com,🎯 全球直连
 - DOMAIN-SUFFIX,battle.net,🎯 全球直连
 - DOMAIN,blzddist1-a.akamaihd.net,🎯 全球直连
 - DOMAIN-SUFFIX,feiliao.com,🎯 全球直连
 - DOMAIN-SUFFIX,pstatp.com,🎯 全球直连
 - DOMAIN-SUFFIX,snssdk.com,🎯 全球直连
 - DOMAIN-SUFFIX,iesdouyin.com,🎯 全球直连
 - DOMAIN-SUFFIX,toutiao.com,🎯 全球直连
 - DOMAIN-SUFFIX,cctv.com,🎯 全球直连
 - DOMAIN-SUFFIX,cctvpic.com,🎯 全球直连
 - DOMAIN-SUFFIX,livechina.com,🎯 全球直连
 - DOMAIN-SUFFIX,didialift.com,🎯 全球直连
 - DOMAIN-SUFFIX,didiglobal.com,🎯 全球直连
 - DOMAIN-SUFFIX,udache.com,🎯 全球直连
 - DOMAIN-SUFFIX,343480.com,🎯 全球直连
 - DOMAIN-SUFFIX,baduziyuan.com,🎯 全球直连
 - DOMAIN-SUFFIX,com-hs-hkdy.com,🎯 全球直连
 - DOMAIN-SUFFIX,czybjz.com,🎯 全球直连
 - DOMAIN-SUFFIX,dandanzan.com,🎯 全球直连
 - DOMAIN-SUFFIX,fjhps.com,🎯 全球直连
 - DOMAIN-SUFFIX,kuyunbo.club,🎯 全球直连
 - DOMAIN-SUFFIX,21cn.com,🎯 全球直连
 - DOMAIN-SUFFIX,hitv.com,🎯 全球直连
 - DOMAIN-SUFFIX,mgtv.com,🎯 全球直连
 - DOMAIN-SUFFIX,iqiyi.com,🎯 全球直连
 - DOMAIN-SUFFIX,iqiyipic.com,🎯 全球直连
 - DOMAIN-SUFFIX,71.am.com,🎯 全球直连
 - DOMAIN-SUFFIX,jd.com,🎯 全球直连
 - DOMAIN-SUFFIX,jd.hk,🎯 全球直连
 - DOMAIN-SUFFIX,jdpay.com,🎯 全球直连
 - DOMAIN-SUFFIX,360buyimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,iciba.com,🎯 全球直连
 - DOMAIN-SUFFIX,ksosoft.com,🎯 全球直连
 - DOMAIN-SUFFIX,meitu.com,🎯 全球直连
 - DOMAIN-SUFFIX,meitudata.com,🎯 全球直连
 - DOMAIN-SUFFIX,meitustat.com,🎯 全球直连
 - DOMAIN-SUFFIX,meipai.com,🎯 全球直连
 - DOMAIN-SUFFIX,duokan.com,🎯 全球直连
 - DOMAIN-SUFFIX,mi-img.com,🎯 全球直连
 - DOMAIN-SUFFIX,miui.com,🎯 全球直连
 - DOMAIN-SUFFIX,miwifi.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiaomi.com,🎯 全球直连
 - DOMAIN-SUFFIX,microsoft.com,🎯 全球直连
 - DOMAIN-SUFFIX,msecnd.net,🎯 全球直连
 - DOMAIN-SUFFIX,office365.com,🎯 全球直连
 - DOMAIN-SUFFIX,outlook.com,🎯 全球直连
 - DOMAIN-SUFFIX,s-microsoft.com,🎯 全球直连
 - DOMAIN-SUFFIX,visualstudio.com,🎯 全球直连
 - DOMAIN-SUFFIX,windows.com,🎯 全球直连
 - DOMAIN-SUFFIX,windowsupdate.com,🎯 全球直连
 - DOMAIN,officecdn-microsoft-com.akamaized.net,🎯 全球直连
 - DOMAIN-SUFFIX,163.com,🎯 全球直连
 - DOMAIN-SUFFIX,126.net,🎯 全球直连
 - DOMAIN-SUFFIX,127.net,🎯 全球直连
 - DOMAIN-SUFFIX,163yun.com,🎯 全球直连
 - DOMAIN-SUFFIX,lofter.com,🎯 全球直连
 - DOMAIN-SUFFIX,netease.com,🎯 全球直连
 - DOMAIN-SUFFIX,ydstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,sina.com,🎯 全球直连
 - DOMAIN-SUFFIX,weibo.com,🎯 全球直连
 - DOMAIN-SUFFIX,weibocdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,sohu.com,🎯 全球直连
 - DOMAIN-SUFFIX,sohucs.com,🎯 全球直连
 - DOMAIN-SUFFIX,sohu-inc.com,🎯 全球直连
 - DOMAIN-SUFFIX,v-56.com,🎯 全球直连
 - DOMAIN-SUFFIX,sogo.com,🎯 全球直连
 - DOMAIN-SUFFIX,sogou.com,🎯 全球直连
 - DOMAIN-SUFFIX,sogoucdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,steampowered.com,🎯 全球直连
 - DOMAIN-SUFFIX,steam-chat.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamgames.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamusercontent.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamcontent.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,🎯 全球直连
 - DOMAIN-SUFFIX,steamstat.us,🎯 全球直连
 - DOMAIN-SUFFIX,gtimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,idqqimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,igamecj.com,🎯 全球直连
 - DOMAIN-SUFFIX,myapp.com,🎯 全球直连
 - DOMAIN-SUFFIX,myqcloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,qq.com,🎯 全球直连
 - DOMAIN-SUFFIX,servicewechat.com,🎯 全球直连
 - DOMAIN-SUFFIX,tencent.com,🎯 全球直连
 - DOMAIN-SUFFIX,tencent-cloud.net,🎯 全球直连
 - DOMAIN-SUFFIX,tenpay.com,🎯 全球直连
 - DOMAIN,file-igamecj.akamaized.net,🎯 全球直连
 - DOMAIN-SUFFIX,jstucdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,zimuzu.io,🎯 全球直连
 - DOMAIN-SUFFIX,zimuzu.tv,🎯 全球直连
 - DOMAIN-SUFFIX,zmz2019.com,🎯 全球直连
 - DOMAIN-SUFFIX,zmzapi.com,🎯 全球直连
 - DOMAIN-SUFFIX,zmzapi.net,🎯 全球直连
 - DOMAIN-SUFFIX,zmzfile.com,🎯 全球直连
 - DOMAIN-SUFFIX,ccgslb.com,🎯 全球直连
 - DOMAIN-SUFFIX,ccgslb.net,🎯 全球直连
 - DOMAIN-SUFFIX,chinanetcenter.com,🎯 全球直连
 - DOMAIN-SUFFIX,meixincdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,ourdvs.com,🎯 全球直连
 - DOMAIN-SUFFIX,staticdn.net,🎯 全球直连
 - DOMAIN-SUFFIX,wangsu.com,🎯 全球直连
 - DOMAIN-SUFFIX,ipip.net,🎯 全球直连
 - DOMAIN-SUFFIX,ip.la,🎯 全球直连
 - DOMAIN-SUFFIX,ip-cdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,ipv6-test.com,🎯 全球直连
 - DOMAIN-SUFFIX,test-ipv6.com,🎯 全球直连
 - DOMAIN-SUFFIX,whatismyip.com,🎯 全球直连
 - DOMAIN-SUFFIX,netspeedtestmaster.com,🎯 全球直连
 - DOMAIN,speedtest.macpaw.com,🎯 全球直连
 - DOMAIN-SUFFIX,awesome-hd.me,🎯 全球直连
 - DOMAIN-SUFFIX,broadcasthe.net,🎯 全球直连
 - DOMAIN-SUFFIX,chdbits.co,🎯 全球直连
 - DOMAIN-SUFFIX,classix-unlimited.co.uk,🎯 全球直连
 - DOMAIN-SUFFIX,empornium.me,🎯 全球直连
 - DOMAIN-SUFFIX,gazellegames.net,🎯 全球直连
 - DOMAIN-SUFFIX,hdchina.org,🎯 全球直连
 - DOMAIN-SUFFIX,hdsky.me,🎯 全球直连
 - DOMAIN-SUFFIX,icetorrent.org,🎯 全球直连
 - DOMAIN-SUFFIX,jpopsuki.eu,🎯 全球直连
 - DOMAIN-SUFFIX,keepfrds.com,🎯 全球直连
 - DOMAIN-SUFFIX,madsrevolution.net,🎯 全球直连
 - DOMAIN-SUFFIX,m-team.cc,🎯 全球直连
 - DOMAIN-SUFFIX,nanyangpt.com,🎯 全球直连
 - DOMAIN-SUFFIX,ncore.cc,🎯 全球直连
 - DOMAIN-SUFFIX,open.cd,🎯 全球直连
 - DOMAIN-SUFFIX,ourbits.club,🎯 全球直连
 - DOMAIN-SUFFIX,passthepopcorn.me,🎯 全球直连
 - DOMAIN-SUFFIX,privatehd.to,🎯 全球直连
 - DOMAIN-SUFFIX,redacted.ch,🎯 全球直连
 - DOMAIN-SUFFIX,springsunday.net,🎯 全球直连
 - DOMAIN-SUFFIX,tjupt.org,🎯 全球直连
 - DOMAIN-SUFFIX,totheglory.im,🎯 全球直连
 - DOMAIN-SUFFIX,acm.org,🎯 全球直连
 - DOMAIN-SUFFIX,acs.org,🎯 全球直连
 - DOMAIN-SUFFIX,aip.org,🎯 全球直连
 - DOMAIN-SUFFIX,ams.org,🎯 全球直连
 - DOMAIN-SUFFIX,annualreviews.org,🎯 全球直连
 - DOMAIN-SUFFIX,aps.org,🎯 全球直连
 - DOMAIN-SUFFIX,ascelibrary.org,🎯 全球直连
 - DOMAIN-SUFFIX,asm.org,🎯 全球直连
 - DOMAIN-SUFFIX,asme.org,🎯 全球直连
 - DOMAIN-SUFFIX,astm.org,🎯 全球直连
 - DOMAIN-SUFFIX,bmj.com,🎯 全球直连
 - DOMAIN-SUFFIX,cambridge.org,🎯 全球直连
 - DOMAIN-SUFFIX,cas.org,🎯 全球直连
 - DOMAIN-SUFFIX,clarivate.com,🎯 全球直连
 - DOMAIN-SUFFIX,ebscohost.com,🎯 全球直连
 - DOMAIN-SUFFIX,emerald.com,🎯 全球直连
 - DOMAIN-SUFFIX,engineeringvillage.com,🎯 全球直连
 - DOMAIN-SUFFIX,icevirtuallibrary.com,🎯 全球直连
 - DOMAIN-SUFFIX,ieee.org,🎯 全球直连
 - DOMAIN-SUFFIX,imf.org,🎯 全球直连
 - DOMAIN-SUFFIX,iop.org,🎯 全球直连
 - DOMAIN-SUFFIX,jamanetwork.com,🎯 全球直连
 - DOMAIN-SUFFIX,jhu.edu,🎯 全球直连
 - DOMAIN-SUFFIX,jstor.org,🎯 全球直连
 - DOMAIN-SUFFIX,karger.com,🎯 全球直连
 - DOMAIN-SUFFIX,libguides.com,🎯 全球直连
 - DOMAIN-SUFFIX,madsrevolution.net,🎯 全球直连
 - DOMAIN-SUFFIX,mpg.de,🎯 全球直连
 - DOMAIN-SUFFIX,myilibrary.com,🎯 全球直连
 - DOMAIN-SUFFIX,nature.com,🎯 全球直连
 - DOMAIN-SUFFIX,oecd-ilibrary.org,🎯 全球直连
 - DOMAIN-SUFFIX,osapublishing.org,🎯 全球直连
 - DOMAIN-SUFFIX,oup.com,🎯 全球直连
 - DOMAIN-SUFFIX,ovid.com,🎯 全球直连
 - DOMAIN-SUFFIX,oxfordartonline.com,🎯 全球直连
 - DOMAIN-SUFFIX,oxfordbibliographies.com,🎯 全球直连
 - DOMAIN-SUFFIX,oxfordmusiconline.com,🎯 全球直连
 - DOMAIN-SUFFIX,pnas.org,🎯 全球直连
 - DOMAIN-SUFFIX,proquest.com,🎯 全球直连
 - DOMAIN-SUFFIX,rsc.org,🎯 全球直连
 - DOMAIN-SUFFIX,sagepub.com,🎯 全球直连
 - DOMAIN-SUFFIX,sciencedirect.com,🎯 全球直连
 - DOMAIN-SUFFIX,sciencemag.org,🎯 全球直连
 - DOMAIN-SUFFIX,scopus.com,🎯 全球直连
 - DOMAIN-SUFFIX,siam.org,🎯 全球直连
 - DOMAIN-SUFFIX,spiedigitallibrary.org,🎯 全球直连
 - DOMAIN-SUFFIX,springer.com,🎯 全球直连
 - DOMAIN-SUFFIX,springerlink.com,🎯 全球直连
 - DOMAIN-SUFFIX,tandfonline.com,🎯 全球直连
 - DOMAIN-SUFFIX,un.org,🎯 全球直连
 - DOMAIN-SUFFIX,uni-bielefeld.de,🎯 全球直连
 - DOMAIN-SUFFIX,webofknowledge.com,🎯 全球直连
 - DOMAIN-SUFFIX,westlaw.com,🎯 全球直连
 - DOMAIN-SUFFIX,wiley.com,🎯 全球直连
 - DOMAIN-SUFFIX,worldbank.org,🎯 全球直连
 - DOMAIN-SUFFIX,worldscientific.com,🎯 全球直连
 - DOMAIN-SUFFIX,cn,🎯 全球直连
 - DOMAIN-SUFFIX,360in.com,🎯 全球直连
 - DOMAIN-SUFFIX,51ym.me,🎯 全球直连
 - DOMAIN-SUFFIX,8686c.com,🎯 全球直连
 - DOMAIN-SUFFIX,abchina.com,🎯 全球直连
 - DOMAIN-SUFFIX,accuweather.com,🎯 全球直连
 - DOMAIN-SUFFIX,aicoinstorge.com,🎯 全球直连
 - DOMAIN-SUFFIX,air-matters.com,🎯 全球直连
 - DOMAIN-SUFFIX,air-matters.io,🎯 全球直连
 - DOMAIN-SUFFIX,aixifan.com,🎯 全球直连
 - DOMAIN-SUFFIX,amd.com,🎯 全球直连
 - DOMAIN-SUFFIX,b612.net,🎯 全球直连
 - DOMAIN-SUFFIX,bdatu.com,🎯 全球直连
 - DOMAIN-SUFFIX,beitaichufang.com,🎯 全球直连
 - DOMAIN-SUFFIX,bjango.com,🎯 全球直连
 - DOMAIN-SUFFIX,booking.com,🎯 全球直连
 - DOMAIN-SUFFIX,bstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,cailianpress.com,🎯 全球直连
 - DOMAIN-SUFFIX,camera360.com,🎯 全球直连
 - DOMAIN-SUFFIX,chinaso.com,🎯 全球直连
 - DOMAIN-SUFFIX,chua.pro,🎯 全球直连
 - DOMAIN-SUFFIX,chuimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,chunyu.mobi,🎯 全球直连
 - DOMAIN-SUFFIX,chushou.tv,🎯 全球直连
 - DOMAIN-SUFFIX,cmbchina.com,🎯 全球直连
 - DOMAIN-SUFFIX,cmbimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,ctrip.com,🎯 全球直连
 - DOMAIN-SUFFIX,dfcfw.com,🎯 全球直连
 - DOMAIN-SUFFIX,docschina.org,🎯 全球直连
 - DOMAIN-SUFFIX,douban.com,🎯 全球直连
 - DOMAIN-SUFFIX,doubanio.com,🎯 全球直连
 - DOMAIN-SUFFIX,douyu.com,🎯 全球直连
 - DOMAIN-SUFFIX,dxycdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,dytt8.net,🎯 全球直连
 - DOMAIN-SUFFIX,eastmoney.com,🎯 全球直连
 - DOMAIN-SUFFIX,eudic.net,🎯 全球直连
 - DOMAIN-SUFFIX,feng.com,🎯 全球直连
 - DOMAIN-SUFFIX,fengkongcloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,frdic.com,🎯 全球直连
 - DOMAIN-SUFFIX,futu5.com,🎯 全球直连
 - DOMAIN-SUFFIX,futunn.com,🎯 全球直连
 - DOMAIN-SUFFIX,gandi.net,🎯 全球直连
 - DOMAIN-SUFFIX,geilicdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,getpricetag.com,🎯 全球直连
 - DOMAIN-SUFFIX,gifshow.com,🎯 全球直连
 - DOMAIN-SUFFIX,godic.net,🎯 全球直连
 - DOMAIN-SUFFIX,hicloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,hongxiu.com,🎯 全球直连
 - DOMAIN-SUFFIX,hostbuf.com,🎯 全球直连
 - DOMAIN-SUFFIX,huxiucdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,huya.com,🎯 全球直连
 - DOMAIN-SUFFIX,infinitynewtab.com,🎯 全球直连
 - DOMAIN-SUFFIX,ithome.com,🎯 全球直连
 - DOMAIN-SUFFIX,java.com,🎯 全球直连
 - DOMAIN-SUFFIX,jidian.im,🎯 全球直连
 - DOMAIN-SUFFIX,kaiyanapp.com,🎯 全球直连
 - DOMAIN-SUFFIX,kaspersky-labs.com,🎯 全球直连
 - DOMAIN-SUFFIX,keepcdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,kkmh.com,🎯 全球直连
 - DOMAIN-SUFFIX,licdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,linkedin.com,🎯 全球直连
 - DOMAIN-SUFFIX,loli.net,🎯 全球直连
 - DOMAIN-SUFFIX,luojilab.com,🎯 全球直连
 - DOMAIN-SUFFIX,maoyan.com,🎯 全球直连
 - DOMAIN-SUFFIX,maoyun.tv,🎯 全球直连
 - DOMAIN-SUFFIX,meituan.com,🎯 全球直连
 - DOMAIN-SUFFIX,meituan.net,🎯 全球直连
 - DOMAIN-SUFFIX,mobike.com,🎯 全球直连
 - DOMAIN-SUFFIX,moke.com,🎯 全球直连
 - DOMAIN-SUFFIX,mubu.com,🎯 全球直连
 - DOMAIN-SUFFIX,myzaker.com,🎯 全球直连
 - DOMAIN-SUFFIX,nim-lang-cn.org,🎯 全球直连
 - DOMAIN-SUFFIX,nvidia.com,🎯 全球直连
 - DOMAIN-SUFFIX,oracle.com,🎯 全球直连
 - DOMAIN-SUFFIX,paypal.com,🎯 全球直连
 - DOMAIN-SUFFIX,paypalobjects.com,🎯 全球直连
 - DOMAIN-SUFFIX,qdaily.com,🎯 全球直连
 - DOMAIN-SUFFIX,qidian.com,🎯 全球直连
 - DOMAIN-SUFFIX,qyer.com,🎯 全球直连
 - DOMAIN-SUFFIX,qyerstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,raychase.net,🎯 全球直连
 - DOMAIN-SUFFIX,ronghub.com,🎯 全球直连
 - DOMAIN-SUFFIX,ruguoapp.com,🎯 全球直连
 - DOMAIN-SUFFIX,s-reader.com,🎯 全球直连
 - DOMAIN-SUFFIX,sankuai.com,🎯 全球直连
 - DOMAIN-SUFFIX,scomper.me,🎯 全球直连
 - DOMAIN-SUFFIX,seafile.com,🎯 全球直连
 - DOMAIN-SUFFIX,sm.ms,🎯 全球直连
 - DOMAIN-SUFFIX,smzdm.com,🎯 全球直连
 - DOMAIN-SUFFIX,snapdrop.net,🎯 全球直连
 - DOMAIN-SUFFIX,snwx.com,🎯 全球直连
 - DOMAIN-SUFFIX,sspai.com,🎯 全球直连
 - DOMAIN-SUFFIX,takungpao.com,🎯 全球直连
 - DOMAIN-SUFFIX,teamviewer.com,🎯 全球直连
 - DOMAIN-SUFFIX,tianyancha.com,🎯 全球直连
 - DOMAIN-SUFFIX,udacity.com,🎯 全球直连
 - DOMAIN-SUFFIX,uning.com,🎯 全球直连
 - DOMAIN-SUFFIX,vmware.com,🎯 全球直连
 - DOMAIN-SUFFIX,weather.com,🎯 全球直连
 - DOMAIN-SUFFIX,weico.cc,🎯 全球直连
 - DOMAIN-SUFFIX,weidian.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiachufang.com,🎯 全球直连
 - DOMAIN-SUFFIX,ximalaya.com,🎯 全球直连
 - DOMAIN-SUFFIX,xinhuanet.com,🎯 全球直连
 - DOMAIN-SUFFIX,xmcdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,yangkeduo.com,🎯 全球直连
 - DOMAIN-SUFFIX,zhangzishi.cc,🎯 全球直连
 - DOMAIN-SUFFIX,zhihu.com,🎯 全球直连
 - DOMAIN-SUFFIX,zhimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,zhuihd.com,🎯 全球直连
 - DOMAIN,download.jetbrains.com,🎯 全球直连
 - DOMAIN,images-cn.ssl-images-amazon.com,🎯 全球直连
 - IP-CIDR,119.28.28.28/32,🎯 全球直连,no-resolve
 - DOMAIN-SUFFIX,smtp,🎯 全球直连
 - DOMAIN-KEYWORD,aria2,🎯 全球直连
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
EOF

cd /home/clash/.config/clash

mkdir dashboard

wget --no-check-certificate https://github.com/haishanh/yacd/archive/gh-pages.zip

unzip gh-pages.zip

mv yacd-gh-pages/ dashboard/

chown -R clash /home/clash/.config/

cat << EOF > /lib/systemd/system/clash@.service
[Unit]
Description=A rule based proxy in Go for %i.
After=network.target
[Service]
Type=simple
User=%i
Restart=on-abort
ExecStart=/usr/local/bin/clash
[Install]
WantedBy=multi-user.target
EOF


systemctl daemon-reload
#设置自启动

systemctl enable clash@clash

systemctl start clash@clash > /dev/null 2>&1

sleep 5
}


dt_iptables(){

temp_ip=(${loc_ip//./ })

jy_ip=${temp_ip[0]}"."${temp_ip[1]}".0.0"

iptables -t nat -N clash
echo "1******************************************************************"
iptables -t nat -N clash_dns
echo "2******************************************************************"
iptables -t nat -A PREROUTING -p tcp --dport 53 -d $jy_ip/16 -j clash_dns
echo "3******************************************************************"
iptables -t nat -A PREROUTING -p udp --dport 53 -d $jy_ip/16 -j clash_dns
echo "4******************************************************************"
iptables -t nat -A PREROUTING -p tcp -j clash
echo "5******************************************************************"

iptables -t nat -A clash_dns -p udp --dport 53 -d $jy_ip/16 -j DNAT --to-destination $loc_ip:53
echo "6******************************************************************"
iptables -t nat -A clash_dns -p tcp --dport 53 -d $jy_ip/16 -j DNAT --to-destination $loc_ip:53
echo "7******************************************************************"
#注意：这里的网段和IP你需要自己适配自己的
iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN
echo "8******************************************************************"
# iptables -t nat -A clash -p tcp --dport 22 -d $loc_ip/24 -j ACCEPT
iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
echo "9******************************************************************"
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892
echo "10******************************************************************"
netfilter-persistent save
echo "11******************************************************************"
netfilter-persistent start
echo "12******************************************************************"
iptables-save  > /etc/iptables/rules.v4
echo "13******************************************************************"
}


set_ip_dns(){

cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*
auto lo
auto  $eth_n
iface $eth_n inet static
  address $loc_ip
  netmask 255.255.255.0
  gateway $gate_ip
  dns-nameservers $dns
  mtu $mtu
  mss $mss
EOF

echo "14******************************************************************"
}

dt_menu() {
 Mainmenu=$(whiptail --clear --ok-button "确定" --backtitle "version:20200324v3" --title "灯塔客户端v2.0" --menu --nocancel "
**********************************************************************************
简介：灯塔客户端v2.0
系统：>=debian9
Youtube：米月
电报群：https://t.me/mi_yue
Youtube频道地址：https://t.im/n21o
**********************************************************************************
请选择需要安装的内容：
    " 22 86 5\
        "1" " 安装灯塔客户端"\
        "4" " 退出" 3>&1 1>&2 2>&3)
    case $Mainmenu in
        1)
        dt_system_dep
        dt_input
        dt_smartdns
        dt_clash
        dt_iptables
        set_ip_dns
        whiptail --title "灯塔客户端安装成功" --msgbox "
*************************************************************************
灯塔客户端安装成功，把需要留学机器的网关和dns改成灯塔客户端ip。软路由请自行修改。
灯塔客户端IP：$loc_ip
Youtube：米月
电报群：https://t.me/mi_yue
Youtube频道地址：https://t.im/n21o
灯塔web页面:http://$loc_ip:9090/ui/
DNS上游修改地址：/etc/smartdns/smartdns.conf
灯塔客户端配置文件地址：/home/clash/.config/clash/config.yaml
*************************************************************************" 18 78
        clear
        ;;
        4)
        #exit
        clear
        whiptail --title "脚本已退出" --msgbox "真希望把你留住" 8 78
        ;;
        esac
}

eth_n=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
GFW_LIST="https://raw.githubusercontent.com/pzwsquare/dt_client/master/black/gfw_domain.conf"
SM="https://github.com/pymumu/smartdns/releases/download/Release30/smartdns.1.2020.02.25-2212.x86_64-debian-all.deb"
CLS="https://github.com/Dreamacro/clash/releases/download/v0.19.0/clash-linux-amd64-v0.19.0.gz"

dt_menu
